### ISSUE TITLE
Webhook from Sonar contains #number of PR instead of branch name 

### ISSUE THREAD

**Issue by juldou** [herlon214/sonarqube-pr-issues#4]
Hello, thank you for your project.

We are considering using it, but we came into an issue, which can also be caused by our settings.

In the code, you are parsing the branch name, but from Sonar Webhook, the data contains PR number (and it fails as it is not valid branch name). From Sonar Webhook (Sonar Enterprise) we are getting following data:

`"branch": {
    "name": "45",
    "type": "PULL_REQUEST",
    "isMain": false,
  }`

I wanted to discuss this with you in advance, but I was not able to find any contact email or anything.

Thank you.

**Comment by juldou** [comment]
I am already working on support for PULL_REQUEST type. Change is trivial.

**Comment by herlon214** [comment]
Hey @juldou thank you very much for helping to build this :muscle: 
Let me know if you need any help

**Comment by juldou** [comment]
Fix of this issue + boolean flag to allow commenting without requesting changes - https://github.com/herlon214/sonarqube-pr-issues/pull/5

If you insist on splitting it to 2 separate PR's, let me know. 

Thank you.
