### ISSUE TITLE
Thread found: Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by PavelA85** [herlon214/sonarqube-pr-issues#7]
After downloading the latest windows version I got an antivirus notification:

![image](https://user-images.githubusercontent.com/2944514/162897644-7dd7c941-d332-4274-98f8-f0121a81deb7.png)

https://github.com/herlon214/sonarqube-pr-issues/releases/download/v0.4.0/sqpr_0.4.0_windows_386.tar.gz

**Comment by herlon214** [comment]
Thanks for reporting, I'm checking what's wrong right now

**Comment by herlon214** [comment]
@PavelA85 that sounds weird. Take a look into the VirusTotal report https://www.virustotal.com/gui/url/c18086b215a11028a7b42f5e8ed45f2ff689b2b3e1574debb280f385ebf746ce?nocache=1

You can also build locally if you prefer.

**Comment by herlon214** [comment]
@PavelA85 I tested all binaries and indeed there are **two windows binaries being flagged as malicious** (which I must say it's a **false positive**). I deleted them from the release download page just to not confuse other people, you can build the project by yourself to use on windows.

https://www.virustotal.com/gui/file/bbcb7388ee9a9c102c87a679fa727dcad6a8a16090db9edacefee418ef9b7d9d/relations

You can also double check every project dependency if you want. This happens with many other go binaries (https://github.com/stripe/stripe-cli/issues/379) and even with go itself (https://go.dev/doc/faq#virus).
